#!/bin/sh /etc/rc.common

START=90
STOP=15

config_apply() {
    # Apply the UCI configuration commands
    uci set system.@system[-1].log_file='/var/log/messages'
    uci commit system
    /etc/init.d/system restart

    uci add firewall rule
    uci set firewall.@rule[-1].name='Allow-ssh'
    uci set firewall.@rule[-1].src='wan'
    uci set firewall.@rule[-1].dest_port='22'
    uci set firewall.@rule[-1].target='ACCEPT'
    uci commit firewall

    uci add firewall rule
    uci set firewall.@rule[-1].name='Block-HTTP-WAN'
    uci set firewall.@rule[-1].src='wan'
    uci set firewall.@rule[-1].proto='tcp'
    uci set firewall.@rule[-1].dest_port='80'
    uci set firewall.@rule[-1].target='ACCEPT'
    uci commit firewall

    uci add firewall rule
    uci set firewall.@rule[-1].name='Block-HTTPS-WAN'
    uci set firewall.@rule[-1].src='wan'
    uci set firewall.@rule[-1].proto='tcp'
    uci set firewall.@rule[-1].dest_port='443'
    uci set firewall.@rule[-1].target='ACCEPT'
    uci commit firewall
    /etc/init.d/firewall restart

    # Create the flag file to indicate the script has been executed
    touch "$FLAG_FILE"
}

boot() {
    # Check if the stamp file exists
    if [ ! -f /etc/config/wan_configured ]; then
        config_apply
        # Remove eth0 from the br-lan device
        uci del_list network.@device[-1].ports='eth0'
        
        # Create the WAN interface if it doesn't exist
        uci set network.wan=interface
        uci set network.wan.ifname='eth0'
        uci set network.wan.proto='dhcp'
        
        # Commit changes and restart network
        uci commit network
        /etc/init.d/network restart
        
        # Touch the stamp file to indicate configuration is done
        touch /etc/config/wan_configured
    fi
}




