#!/bin/sh /etc/rc.common

START=99
STOP=01

USE_PROCD=1
PROG=/usr/bin/tedd
LOGFILE=/var/log/tedd.log

start_service() {
    procd_open_instance
    procd_set_param command $PROG
    procd_set_param stdout 1 # log stdout to logfile
    procd_set_param stderr 1 # log stderr to logfile
    procd_set_param file $LOGFILE
    procd_close_instance
}

stop_service() {
    killall tedd
}

restart() {
    stop_service
    start_service
}

status() {
    if pgrep tedd > /dev/null; then
        echo "Service is running"
    else
        echo "Service is stopped"
    fi
}
