#!/bin/sh

# Define the flag file
FLAG_FILE="/etc/first_boot_completed"

# Check if the flag file exists
if [ ! -f "$FLAG_FILE" ]; then

    # Apply the UCI configuration commands
    uci set system.@system[-1].log_file='/var/log/messages'
    uci commit system
    /etc/init.d/system restart

    uci del network.@device[0].ports
    uci set network.wan=interface
    uci set network.wan.device='eth0'
    uci set network.wan.proto='dhcp' 
    uci commit network
    /etc/init.d/network restart

    uci set firewall.@rule[-1]=rule
    uci set firewall.@rule[-1].name='Allow-SSH-WAN'
    uci set firewall.@rule[-1].src='wan'
    uci set firewall.@rule[-1].dest='lan'
    uci set firewall.@rule[-1].proto='tcp'
    uci set firewall.@rule[-1].dest_port='22'
    uci set firewall.@rule[-1].target='ACCEPT'
    uci commit firewall
    /etc/init.d/firewall restart

    # Create the flag file to indicate the script has been executed
    touch "$FLAG_FILE"
else
    echo "The first boot script has already been executed. Skipping..."
fi